post:
  title:
    minimum_length: 15
    maximum_length: 150
  body:
    minimum_length: 30
tag:
  amount:
    minimum: 1
    maximum: 5
  popular_lenth: 25
comment:
  text:
    minimum_length: 10
    maximum_length: 600
